In [2]:
# data exploration
import pandas as pd

df = pd.read_csv("articles.csv")

# General info
print("DF dimensions:")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nMemory size:")
mem_db = df.memory_usage(deep=True).sum() / 1024**2
print(f"{mem_db:.2f} MB")

print("\nFirst rows:")
print(df.head())

# Detailed info
print("\nTypes and nulls:")
df.info()

DF dimensions:
Rows: 105542
Columns: 25

Memory size:
106.25 MB

First rows:
   article_id  product_code          prod_name  product_type_no  \
0   108775015        108775          Strap top              253
1   108775044        108775          Strap top              253
2   108775051        108775      Strap top (1)              253
3   110065001        110065  OP T-shirt (Idro)              306
4   110065002        110065  OP T-shirt (Idro)              306

  product_type_name  product_group_name  graphical_appearance_no  \
0          Vest top  Garment Upper body                  1010016
1          Vest top  Garment Upper body                  1010016
2          Vest top  Garment Upper body                  1010017
3               Bra           Underwear                  1010016
4               Bra           Underwear                  1010016

  graphical_appearance_name  colour_group_code colour_group_name  ...  \
0                     Solid                  9             Black  ...
1                     Solid                 10             White  ...
2                    Stripe                 11         Off White  ...
3                     Solid                  9             Black  ...
4                     Solid                 10             White  ...

   department_name index_code        index_name index_group_no  \
0     Jersey Basic          A        Ladieswear              1
1     Jersey Basic          A        Ladieswear              1
2     Jersey Basic          A        Ladieswear              1
3   Clean Lingerie          B  Lingeries/Tights              1
4   Clean Lingerie          B  Lingeries/Tights              1

   index_group_name section_no            section_name garment_group_no  \
0        Ladieswear         16  Womens Everyday Basics             1002
1        Ladieswear         16  Womens Everyday Basics             1002
2        Ladieswear         16  Womens Everyday Basics             1002
3        Ladieswear         61         Womens Lingerie             1017
4        Ladieswear         61         Womens Lingerie             1017

   garment_group_name                                        detail_desc
0        Jersey Basic            Jersey top with narrow shoulder straps.
1        Jersey Basic            Jersey top with narrow shoulder straps.
2        Jersey Basic            Jersey top with narrow shoulder straps.
3   Under-, Nightwear  Microfibre T-shirt bra with underwired, moulde...
4   Under-, Nightwear  Microfibre T-shirt bra with underwired, moulde...

[5 rows x 25 columns]

Types and nulls:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int64(11), object(14)
memory usage: 20.1+ MB

In [3]:
# data exploration
import pandas as pd

df = pd.read_csv("customers.csv")

# General info
print("DF dimensions:")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nMemory size:")
mem_db = df.memory_usage(deep=True).sum() / 1024**2
print(f"{mem_db:.2f} MB")

print("\nFirst rows:")
print(df.head())

# Detailed info
print("\nTypes and nulls:")
df.info()

DF dimensions:
Rows: 1371980
Columns: 7

Memory size:
470.60 MB

First rows:
                                         customer_id   FN  Active  \
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...  NaN     NaN
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...  NaN     NaN
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...  NaN     NaN
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...  NaN     NaN
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...  1.0     1.0

  club_member_status fashion_news_frequency   age  \
0             ACTIVE                   NONE  49.0
1             ACTIVE                   NONE  25.0
2             ACTIVE                   NONE  24.0
3             ACTIVE                   NONE  54.0
4             ACTIVE              Regularly  52.0

                                         postal_code
0  52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1  2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2  64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3  5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4  25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

Types and nulls:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  object
 4   fashion_news_frequency  1355969 non-null  object
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(3), object(4)
memory usage: 73.3+ MB

In [6]:
# --- Descriptive Statistical Analysis ---
import pandas as pd

# Load dataset
df = pd.read_csv("articles.csv")  # ajusta la ruta si es necesario

# General Information
print("General Information:")
df.info()

# Summary Statistics (all types) 
print("\nDescriptive Statistics (all variables):")
desc = df.describe(include='all')
display(desc)

# Detailed per-column summary 
summary_list = []

for col in df.columns:
    dtype = df[col].dtype
    
    # Numeric columns
    if pd.api.types.is_numeric_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": str(dtype),
            "Mean": df[col].mean(),
            "Median": df[col].median(),
            "Std Dev": df[col].std(),
            "Min": df[col].min(),
            "25%": df[col].quantile(0.25),
            "50%": df[col].quantile(0.50),
            "75%": df[col].quantile(0.75),
            "Max": df[col].max(),
            "Unique": df[col].nunique(),
            "Missing": df[col].isna().sum()
        })
        
    # Categorical columns
    elif pd.api.types.is_object_dtype(df[col]) or pd.api.types.is_categorical_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": str(dtype),
            "Unique categories": df[col].nunique(),
            "Most frequent (mode)": df[col].mode().iloc[0] if not df[col].mode().empty else None,
            "Frequency of mode": df[col].value_counts().iloc[0] if not df[col].value_counts().empty else None,
            "Missing": df[col].isna().sum()
        })
        
    # Datetime columns
    elif pd.api.types.is_datetime64_any_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": "datetime",
            "Min date": df[col].min(),
            "Max date": df[col].max(),
            "Missing": df[col].isna().sum()
        })

# Convert to DataFrame for better visualization
summary_df = pd.DataFrame(summary_list)
display(summary_df)

General Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int64(11), object(14)
memory usage: 20.1+ MB

Descriptive Statistics (all variables):

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
count,1.055420e+05,105542.000000,105542,105542.000000,105542,105542,1.055420e+05,105542,105542.000000,105542,...,105542,105542,105542,105542.000000,105542,105542.000000,105542,105542.000000,105542,105126
unique,NaN,NaN,45875,NaN,131,19,NaN,30,NaN,50,...,250,10,10,NaN,5,NaN,56,NaN,21,43404
top,NaN,NaN,Dragonfly dress,NaN,Trousers,Garment Upper body,NaN,Solid,NaN,Black,...,Jersey,A,Ladieswear,NaN,Ladieswear,NaN,Womens Everyday Collection,NaN,Jersey Fancy,T-shirt in printed cotton jersey.
freq,NaN,NaN,98,NaN,11169,42741,NaN,49747,NaN,22670,...,4604,26001,26001,NaN,39737,NaN,7295,NaN,21445,159
mean,6.984246e+08,698424.563378,NaN,234.861875,NaN,NaN,1.009515e+06,NaN,32.233822,NaN,...,NaN,NaN,NaN,3.171534,NaN,42.664219,NaN,1010.438290,NaN,NaN
std,1.284624e+08,128462.384432,NaN,75.049308,NaN,NaN,2.241359e+04,NaN,28.086154,NaN,...,NaN,NaN,NaN,4.353234,NaN,23.260105,NaN,6.731023,NaN,NaN
min,1.087750e+08,108775.000000,NaN,-1.000000,NaN,NaN,-1.000000e+00,NaN,-1.000000,NaN,...,NaN,NaN,NaN,1.000000,NaN,2.000000,NaN,1001.000000,NaN,NaN
25%,6.169925e+08,616992.500000,NaN,252.000000,NaN,NaN,1.010008e+06,NaN,9.000000,NaN,...,NaN,NaN,NaN,1.000000,NaN,20.000000,NaN,1005.000000,NaN,NaN
50%,7.022130e+08,702213.000000,NaN,259.000000,NaN,NaN,1.010016e+06,NaN,14.000000,NaN,...,NaN,NaN,NaN,2.000000,NaN,46.000000,NaN,1009.000000,NaN,NaN
75%,7.967030e+08,796703.000000,NaN,272.000000,NaN,NaN,1.010016e+06,NaN,52.000000,NaN,...,NaN,NaN,NaN,4.000000,NaN,61.000000,NaN,1017.000000,NaN,NaN
max,9.594610e+08,959461.000000,NaN,762.000000,NaN,NaN,1.010029e+06,NaN,93.000000,NaN,...,NaN,NaN,NaN,26.000000,NaN,97.000000,NaN,1025.000000,NaN,NaN

,Variable,Type,Mean,Median,Std Dev,Min,25%,50%,75%,Max,Unique,Missing,Unique categories,Most frequent (mode),Frequency of mode
0,article_id,int64,6.984246e+08,702213001.5,1.284624e+08,108775015.0,616992501.0,702213001.5,7.967030e+08,959461001.0,105542.0,0,NaN,NaN,NaN
1,product_code,int64,6.984246e+05,702213.0,1.284624e+05,108775.0,616992.5,702213.0,7.967030e+05,959461.0,47224.0,0,NaN,NaN,NaN
2,prod_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,45875.0,Dragonfly dress,98.0
3,product_type_no,int64,2.348619e+02,259.0,7.504931e+01,-1.0,252.0,259.0,2.720000e+02,762.0,132.0,0,NaN,NaN,NaN
4,product_type_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,131.0,Trousers,11169.0
5,product_group_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,19.0,Garment Upper body,42741.0
6,graphical_appearance_no,int64,1.009515e+06,1010016.0,2.241359e+04,-1.0,1010008.0,1010016.0,1.010016e+06,1010029.0,30.0,0,NaN,NaN,NaN
7,graphical_appearance_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,30.0,Solid,49747.0
8,colour_group_code,int64,3.223382e+01,14.0,2.808615e+01,-1.0,9.0,14.0,5.200000e+01,93.0,50.0,0,NaN,NaN,NaN
9,colour_group_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,50.0,Black,22670.0
10,perceived_colour_value_id,int64,3.206183e+00,4.0,1.563839e+00,-1.0,2.0,4.0,4.000000e+00,7.0,8.0,0,NaN,NaN,NaN
11,perceived_colour_value_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,8.0,Dark,42706.0
12,perceived_colour_master_id,int64,7.807972e+00,5.0,5.376727e+00,-1.0,4.0,5.0,1.100000e+01,20.0,20.0,0,NaN,NaN,NaN
13,perceived_colour_master_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,20.0,Black,22585.0
14,department_no,int64,4.532778e+03,4222.0,2.712692e+03,1201.0,1676.0,4222.0,7.389000e+03,9989.0,299.0,0,NaN,NaN,NaN
15,department_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,250.0,Jersey,4604.0
16,index_code,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10.0,A,26001.0
17,index_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10.0,Ladieswear,26001.0
18,index_group_no,int64,3.171534e+00,2.0,4.353234e+00,1.0,1.0,2.0,4.000000e+00,26.0,5.0,0,NaN,NaN,NaN
19,index_group_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5.0,Ladieswear,39737.0
20,section_no,int64,4.266422e+01,46.0,2.326010e+01,2.0,20.0,46.0,6.100000e+01,97.0,57.0,0,NaN,NaN,NaN
21,section_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56.0,Womens Everyday Collection,7295.0
22,garment_group_no,int64,1.010438e+03,1009.0,6.731023e+00,1001.0,1005.0,1009.0,1.017000e+03,1025.0,21.0,0,NaN,NaN,NaN
23,garment_group_name,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,21.0,Jersey Fancy,21445.0
24,detail_desc,object,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,416,43404.0,T-shirt in printed cotton jersey.,159.0

In [7]:
# --- Descriptive Statistical Analysis ---
import pandas as pd

# Load dataset
df = pd.read_csv("customers.csv")  # ajusta la ruta si es necesario

# General Information
print("General Information:")
df.info()

# Summary Statistics (all types) 
print("\nDescriptive Statistics (all variables):")
desc = df.describe(include='all')
display(desc)

# Detailed per-column summary 
summary_list = []

for col in df.columns:
    dtype = df[col].dtype
    
    # Numeric columns
    if pd.api.types.is_numeric_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": str(dtype),
            "Mean": df[col].mean(),
            "Median": df[col].median(),
            "Std Dev": df[col].std(),
            "Min": df[col].min(),
            "25%": df[col].quantile(0.25),
            "50%": df[col].quantile(0.50),
            "75%": df[col].quantile(0.75),
            "Max": df[col].max(),
            "Unique": df[col].nunique(),
            "Missing": df[col].isna().sum()
        })
        
    # Categorical columns
    elif pd.api.types.is_object_dtype(df[col]) or pd.api.types.is_categorical_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": str(dtype),
            "Unique categories": df[col].nunique(),
            "Most frequent (mode)": df[col].mode().iloc[0] if not df[col].mode().empty else None,
            "Frequency of mode": df[col].value_counts().iloc[0] if not df[col].value_counts().empty else None,
            "Missing": df[col].isna().sum()
        })
        
    # Datetime columns
    elif pd.api.types.is_datetime64_any_dtype(df[col]):
        summary_list.append({
            "Variable": col,
            "Type": "datetime",
            "Min date": df[col].min(),
            "Max date": df[col].max(),
            "Missing": df[col].isna().sum()
        })

# Convert to DataFrame for better visualization
summary_df = pd.DataFrame(summary_list)
display(summary_df)

General Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  object
 4   fashion_news_frequency  1355969 non-null  object
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(3), object(4)
memory usage: 73.3+ MB

Descriptive Statistics (all variables):

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
count,1371980,476930.0,464404.0,1365918,1355969,1.356119e+06,1371980
unique,1371980,NaN,NaN,3,3,NaN,352899
top,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,NaN,2c29ae653a9282cce4151bd87643c907644e09541abc28...
freq,1,NaN,NaN,1272491,877711,NaN,120303
mean,NaN,1.0,1.0,NaN,NaN,3.638696e+01,NaN
std,NaN,0.0,0.0,NaN,NaN,1.431363e+01,NaN
min,NaN,1.0,1.0,NaN,NaN,1.600000e+01,NaN
25%,NaN,1.0,1.0,NaN,NaN,2.400000e+01,NaN
50%,NaN,1.0,1.0,NaN,NaN,3.200000e+01,NaN
75%,NaN,1.0,1.0,NaN,NaN,4.900000e+01,NaN
max,NaN,1.0,1.0,NaN,NaN,9.900000e+01,NaN

,Variable,Type,Unique categories,Most frequent (mode),Frequency of mode,Missing,Mean,Median,Std Dev,Min,25%,50%,75%,Max,Unique
0,customer_id,object,1371980.0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FN,float64,NaN,NaN,NaN,895050,1.000000,1.0,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
2,Active,float64,NaN,NaN,NaN,907576,1.000000,1.0,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
3,club_member_status,object,3.0,ACTIVE,1272491.0,6062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,fashion_news_frequency,object,3.0,NONE,877711.0,16011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,age,float64,NaN,NaN,NaN,15861,36.386965,32.0,14.313628,16.0,24.0,32.0,49.0,99.0,84.0
6,postal_code,object,352899.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,120303.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN